---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAP 在 AWS 中具有存储配置限制，可提供可靠的操作。为获得最佳性能，请勿将系统配置为最大值。 
---
= AWS 中的存储限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 具有存储配置限制，可提供可靠的操作。为获得最佳性能，请勿将系统配置为最大值。



== 按许可证计算的最大系统容量

Cloud Volumes ONTAP 系统的最大系统容量取决于其许可证。最大系统容量包括基于磁盘的存储以及用于数据分层的对象存储。NetApp 不支持超过此限制。

对于某些 HA 配置，磁盘限制会阻止您单独使用磁盘来达到容量限制。在这些情况下，您可以通过达到容量限制 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["将非活动数据分层到对象存储"^]。有关详细信息，请参见以下容量和磁盘限制。

[cols="25,75"]
|===
| 许可证 | 最大系统容量（磁盘 + 对象存储） 


| 免费 | 500 GiB 


| PAYGO 探索 | 2 TiB （ Explore 不支持数据分层） 


| PAYGO 标准 | 10 TiB 


| PAYGO 高级版 | 368 TiB 


| 基于节点的许可证 | 每个许可证 368 TiB 


| 基于容量的许可证 | 2 个 PIB 
|===
容量限制适用于整个 HA 对。不是每个节点。例如，如果使用高级版许可证，则两个节点之间的容量最多可达 368 TiB 。

不可以。AWS HA 对中的数据会在节点之间同步镜像，以便在发生故障时可以使用这些数据。例如，如果您在节点 A 上购买了 8 TiB 磁盘，则 Cloud Manager 还会在节点 B 上分配一个 8 TiB 磁盘，用于镜像数据。虽然配置了 16 TiB 的容量，但许可证限制仅会计入 8 TiB 的容量。



== EC2 实例的磁盘和分层限制

Cloud Volumes ONTAP 使用 EBS 卷作为磁盘，最大磁盘大小为 16 TiB 。以下各节按 EC2 实例类型显示了磁盘和分层限制，因为许多 EC2 实例类型具有不同的磁盘限制。单节点系统和 HA 对之间的磁盘限制也不同。

以下磁盘限制特定于包含用户数据的磁盘。这些限制不包括启动磁盘和根磁盘。


NOTE: 现在，您可以为 Cloud Volumes ONTAP BYOL 系统购买多个基于节点的许可证，以分配 368 TiB 以上的容量。您可以为单节点系统或 HA 对购买的许可证数量不受限制。请注意，磁盘限制可能会阻止您单独使用磁盘来达到容量限制。您可以通过超出磁盘限制 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["将非活动数据分层到对象存储"^]。 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-node-licenses.html["了解如何向 Cloud Volumes ONTAP 添加其他系统许可证"^]。



=== 具有高级许可证的单个节点

[cols="18,18,32,32"]
|===
| 实例系列 | 每个节点的最大磁盘数 | 单独使用磁盘时的最大系统容量 | 使用磁盘和数据分层的最大系统容量 


| c5 ， m5 和 R5 实例 | 22. | 352 TiB | 368 TiB 


| c4 ， m4 和 r4 实例 | 34 | 368 TiB | 368 TiB 
|===


=== 采用基于节点的许可的单节点

[cols="18,18,16,16,16,16"]
|===
| 实例系列 | 每个节点的最大磁盘数 2+| 使用一个许可证时的最大系统容量 2+| 使用多个许可证时的最大系统容量 


2+|  | * 仅磁盘 * | * 磁盘 + 数据分层 * | * 仅磁盘 * | * 磁盘 + 数据分层 * 


| c5 ， m5 和 R5 实例 | 22. | 352 TiB | 368 TiB | 352 TiB | 每个许可证 368 TiB x 


| c4 ， m4 和 r4 实例 | 34 | 368 TiB | 368 TiB | 544 TiB | 每个许可证 368 TiB x 
|===


=== 具有基于容量的许可的单个节点

[cols="18,18,32,32"]
|===
| 实例系列 | 每个节点的最大磁盘数 | 单独使用磁盘时的最大系统容量 | 使用磁盘和数据分层的最大系统容量 


| c5 ， m5 和 R5 实例 | 22. | 352 TiB | 2 个 PIB 


| c4 ， m4 和 r4 实例 | 34 | 544 TiB | 2 个 PIB 
|===


=== 具有高级许可证的 HA 对

[cols="18,18,32,32"]
|===
| 实例系列 | 每个节点的最大磁盘数 | 单独使用磁盘时的最大系统容量 | 使用磁盘和数据分层的最大系统容量 


| c5 ， m5 和 R5 实例 | 19 | 304 TiB | 368 TiB 


| c4 ， m4 和 r4 实例 | 31 | 368 TiB | 368 TiB 
|===


=== 采用基于节点的许可的 HA 对

[cols="18,18,16,16,16,16"]
|===
| 实例系列 | 每个节点的最大磁盘数 2+| 使用一个许可证时的最大系统容量 2+| 使用多个许可证时的最大系统容量 


2+|  | * 仅磁盘 * | * 磁盘 + 数据分层 * | * 仅磁盘 * | * 磁盘 + 数据分层 * 


| c5 ， m5 和 R5 实例 | 19 | 304 TiB | 368 TiB | 304 TiB | 每个许可证 368 TiB x 


| c4 ， m4 和 r4 实例 | 31 | 368 TiB | 368 TiB | 496 TiB | 每个许可证 368 TiB x 
|===


=== 采用基于容量的许可的 HA 对

[cols="18,18,32,32"]
|===
| 实例系列 | 每个节点的最大磁盘数 | 单独使用磁盘时的最大系统容量 | 使用磁盘和数据分层的最大系统容量 


| c5 ， m5 和 R5 实例 | 19 | 304 TiB | 2 个 PIB 


| c4 ， m4 和 r4 实例 | 31 | 496 TiB | 2 个 PIB 
|===


== 聚合限制

Cloud Volumes ONTAP 使用 AWS 卷作为磁盘，并将其分组为 _aggregodes_ 。聚合可为卷提供存储。

[cols="2*"]
|===
| 参数 | limit 


| 聚合的最大数量 | 单节点：与磁盘限制 HA 对相同：一个节点中 18 个 ^1^ 


| 最大聚合大小 | 96 TiB 原始容量 ^2^ 


| 每个聚合的磁盘数 | 1-6 ^3^ 


| 每个聚合的最大 RAID 组数 | 1. 
|===
注释：

. 无法在 HA 对中的两个节点上创建 19 个聚合，因为这样做会超出数据磁盘限制。
. 聚合容量限制基于构成聚合的磁盘。此限制不包括用于数据分层的对象存储。
. 聚合中的所有磁盘大小必须相同。




== 逻辑存储限制

[cols="22,22,56"]
|===
| 逻辑存储 | 参数 | limit 


| * 存储 VM （ SVM ） * | Cloud Volumes ONTAP 的最大数量（ HA 对或单个节点）  a| 
具有 BYOL* 的 * c5 ， m5 和 R5 实例在自带许可证（ BYOL ）时， c5 ， m5 和 R5 实例类型支持以下数量的 Storage VM ：

* 12 个 Storage VM ，具有单节点系统
* 8 个具有 HA 对的 Storage VM



NOTE: 一个 Storage VM 可跨越整个 Cloud Volumes ONTAP 系统（ HA 对或单个节点）。

默认情况下，除了 Cloud Volumes ONTAP 附带的第一个 Storage VM 之外，每个额外的 _data-Served_SVM 都需要附加许可证。请联系您的客户团队以获取 SVM 附加许可证。

您为灾难恢复（ DR ）配置的 Storage VM 不需要附加许可证（它们是免费的），但它们会计入 Storage VM 限制。^1 ， 2^

* 所有其他配置 * 支持一个提供数据的 Storage VM 和一个用于灾难恢复的目标 Storage VM 。^2^

一个 Storage VM 可跨越整个 Cloud Volumes ONTAP 系统（ HA 对或单个节点）。



.2+| * 文件 * | 最大大小 | 16 TiB 


| 每个卷的上限 | 取决于卷大小，最多 20 亿个 


| * FlexClone 卷 * | 分层克隆深度 ^3^ | 499 


.3+| * FlexVol 卷 * | 每个节点的上限 | 500 


| 最小大小 | 20 MB 


| 最大大小 | 100 TiB 


| * qtree* | 每个 FlexVol 卷的上限 | 4,995 


| * Snapshot 副本 * | 每个 FlexVol 卷的上限 | 1,023 
|===
注释：

. 例如，如果一个 HA 对上有 8 个提供数据的 Storage VM ，则表示已达到限制，无法再创建任何其他 Storage VM 。另一个 HA 对也是如此，该 HA 对配置了 8 个存储 VM 用于灾难恢复—您已达到限制，无法再创建任何 Storage VM 。
. 如果源 Storage VM 发生中断，您可以激活目标 Storage VM 以进行数据访问。Cloud Manager 不为 Storage VM 灾难恢复提供任何设置或编排支持。您必须使用 System Manager 或 CLI 。
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["《 SVM 灾难恢复准备快速指南》"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["《 SVM 灾难恢复快速指南》"^]


. 分层克隆深度是可以从单个 FlexVol 卷创建的 FlexClone 卷嵌套层次结构的最大深度。




== iSCSI 存储限制

[cols="3*"]
|===
| iSCSI 存储 | 参数 | limit 


.4+| * LUN * | 每个节点的上限 | 1,024 


| LUN 映射的最大数量 | 1,024 


| 最大大小 | 16 TiB 


| 每个卷的上限 | 512 


| * igroup* | 每个节点的上限 | 256 


.2+| * 启动程序 * | 每个节点的上限 | 512 


| 每个 igroup 的最大值 | 128. 


| * iSCSI 会话 * | 每个节点的上限 | 1,024 


.2+| * LIF* | 每个端口的上限 | 32 


| 每个端口集的最大值 | 32 


| * 端口集 * | 每个节点的上限 | 256 
|===